name: 
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - datasets
  - git-lfs
  - jupyterlab
  - matplotlib
  - numpy
  - onnx
  - pandas
  - pillow
  - pip
  - python=3.11
  - pytorch
  - pytorch-cuda=11.8
  - scikit-image
  - scikit-learn
  - torchaudio
  - torchvision
  - onnx
  - pip:
    - onnxruntime-gpu==1.21.1
    - wavemix==0.2.4
    - torchsr
