#make sure channel priority is set to strict so cuda pytorch & cuda are used
name: crack_pipeline
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # or match your CUDA version
  - onnx
  - onnxruntime
  - matplotlib
  - scikit-image
  - scikit-learn
  - numpy
  - pandas
  - pillow
  - jupyterlab
  - pip:
      - einops
      - pywavelets
      - kaggle
