[workspace]
authors = ["Adam Camerer <ajc3xc@umsystem.edu>"]
channels = ["conda-forge"]
name = "paddle_environment"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9"
pip = ">=25.1.1,<26"

[pypi-dependencies]
paddlepaddle-gpu = "==2.6.0"
#opencv-python-headless = "*"
#onnx = ">=1.18.0, <2"
setuptools = "*"
scikit-learn = "*"
tqdm = "*"
scipy = "*"
pyyaml = "*"
visualdl = "*"
prettytable = "*"
numpy = "<2"
#opencv-python-headless = ">=4.11.0.86, <5"
#opencv-python-headless = ">=4.8, < 4.9"
nvidia-cublas-cu11 = ">=11.11.3.6, <12"
#paddleseg = ">=2.8.0, <3"
#paddleseg = ">3"

#then do this
#pip install -v -e .
#pip install opencv-python-headless==4.8.1.78
