[workspace]
authors = ["Adam Camerer <ajc3xc@umsystem.edu>"]
channels = ["nvidia", "pytorch", "conda-forge"]
name = "super_resolution"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
datasets = "*"
git-lfs = "*"
jupyterlab = "*"
matplotlib = "*"
numpy = "*"
onnx = "*"
pandas = "*"
pillow = "*"
pip = "*"
python = "3.11.*"
pytorch = "*"
pytorch-cuda = "11.8.*"
scikit-image = "*"
scikit-learn = "*"
torchaudio = "*"
torchvision = "*"

[pypi-dependencies]
onnxruntime-gpu = "==1.21.1"
wavemix = "==0.2.4"
torchsr = "*"
