[workspace]
authors = ["Adam Camerer <ajc3xc@umsystem.edu>"]
channels = ["conda-forge", "pytorch"]
name = "super_resolution"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
datasets = "*"
git-lfs = "*"
jupyterlab = "*"
matplotlib = "*"
numpy = "*"
onnx = "*"
openvino = "*"
# openvino-dev = "*"        # 🔑 tools like Model Optimizer
pandas = "*"
pillow = "*"
pip = "*"
python = "3.11.*"
scikit-image = "*"
scikit-learn = "*"
torchaudio = "*"
torchvision = "*"

# Optional — only activate once your NVIDIA GPU is available
# pytorch = "*"
# pytorch-cuda = "11.8.*"

[pypi-dependencies]
onnxruntime = "==1.21.1"  # 🔧 optimized for CPU
wavemix = "==0.2.4"
torchsr = "*"
