#make sure channel priority is set to strict so cuda pytorch & cuda are used
name: crack_pipeline
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # or match your CUDA version
  - onnx
  - datasets
  - matplotlib
  - scikit-image
  - scikit-learn
  - numpy
  - pandas
  - pillow
  - jupyterlab
  - kaggle
  - pip:
      - einops
      - wavemix
      - huggingface_hub=0.21.4
      - super-image
      - onnxruntime-gpu

#do this if running skimage I believe: export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
