[project]
authors = ["Adam Camerer <ajc3xc@umsystem.edu>"]
channels  = ["rapidsai", "conda-forge"]
name = "cucim"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python      = "==3.10"
cuda-version = "==11.8"
cudatoolkit = "==11.8"
cupy        = "*"
cucim = "==23.4.0"
numpy = "<2"

[tasks]
# Optional: a one-liner to run your script
test-skel   = "python test_skeleton.py"

[pypi-dependencies]
matplotlib = ">=3.10.3, <4"
pandas = ">=2.3.0, <3"
skan = ">=0.12.2, <0.13"
sknw = ">=0.15, <0.16"
cython = ">=3.1.2, <4"

#pip install numpy<2
subpixel-edges = "*"
phycv = "*"
#torch = "*"
#torchvision = "*"
#scikit-image = "*"
#opencv-python-headless = "*"

